version: '2'
services:
  internship_tracker:  
    restart: always
    ports:
      - "5000:80"
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST=www.internship.team
      - LETSENCRYPT_HOST=www.internship.team
      - APP_SECRET=2MsRPk9ZXjUi6YEfLwrhM9ftVvgZpDhHWqm2gboIDLE=  
